version: "3.9"
services:
  orchestrator:
    build: ../orchestrator
    environment:
      - ANALYZER_BASE=http://static_analyzer:8060
      - REPORTER_BASE=http://reporter:8090
      - TI_BASE=http://ti:8070
      - SANDBOX_BASE=http://sandbox:8050
    ports:
      - "8080:8080"
    volumes:
      - ../orchestrator/app/uploads:/app/uploads
  reporter:
    build: ../reporter-service
    ports:
      - "8090:8090"
    volumes:
      - ../reporter-service/app/exports:/app/exports
  ti:
    build: ../ti-enrichment
    environment:
      - VT_API_KEY
    ports:
      - "8070:8070"
  static_analyzer:
    build: ../static-analyzer
    ports:
      - "8060:8060"
  sandbox:
    build: ../sandbox-native
    ports:
      - "8050:8050"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml:ro
    command: [
      "--config.file=/etc/prometheus/prometheus.yml",
      "--web.enable-lifecycle"
    ]
    ports:
      - "9090:9090"
    depends_on:
      - orchestrator
      - reporter
      - ti
      - static_analyzer
      - sandbox
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
