apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-analyzer
  namespace: zorbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-analyzer
  template:
    metadata:
      labels:
        app: static-analyzer
    spec:
      containers:
        - name: static-analyzer
          image: zorbox/static-analyzer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8060
---
apiVersion: v1
kind: Service
metadata:
  name: static-analyzer
  namespace: zorbox
spec:
  selector:
    app: static-analyzer
  ports:
    - name: http
      port: 8060
      targetPort: 8060

